[package]
name = "laby_common"
version = "0.1.4"
edition = "2021"
license = "MIT"
description = "Shared code required by laby"
repository = "https://github.com/chiyadev/laby"

[dependencies]
raw-cpuid = "10"
itoap = "1"
ryu = "1"
